apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: modul2
  name: modul2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modul2
  template:
    metadata:
      labels:
        app: modul2
    spec:
      containers:
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: modul2
        env:
          - name: HTTP_PORT
            value: "8080"


---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: modul2-netpol
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: modul2
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: modul1
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: modul1