services:

  redis1:
    container_name: redis1
    image: centos:7
    entrypoint: sleep 9999999999

  redis2:
    container_name: redis2
    image: centos:7
    entrypoint: sleep 9999999999

  redis3:
    container_name: redis3
    image: centos:7
    entrypoint: sleep 9999999999
