apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-frontend
  name: app-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: front-cont
        env:
          - name: backend-address
            value: backend-svc.default.svc.cluster.local

