---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-volume-postgres
spec:
  storageClassName: local-storage-postgres
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi