apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-front-back
  name: app-front-back
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-front-back
  template:
    metadata:
      labels:
        app: app-front-back
    spec:
      containers:
      - image: praqma/network-multitool:alpine-extra
        imagePullPolicy: IfNotPresent
        name: back-cont
        env:
          - name: HTTP_PORT
            value: "8080"
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: front-cont

