resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.

    [all]
    k8s-master1 ansible_host=${yandex_compute_instance.k8s-master1.network_interface.0.nat_ip_address}  # ip=10.3.0.1 etcd_member_name=etcd1
    k8s-worker1 ansible_host=${yandex_compute_instance.k8s-worker1.network_interface.0.nat_ip_address}  # ip=10.3.0.2 etcd_member_name=etcd2
    k8s-worker2 ansible_host=${yandex_compute_instance.k8s-worker2.network_interface.0.nat_ip_address}  # ip=10.3.0.3 etcd_member_name=etcd3
    k8s-worker3 ansible_host=${yandex_compute_instance.k8s-worker3.network_interface.0.nat_ip_address}  # ip=10.3.0.4 etcd_member_name=etcd4
    k8s-worker4 ansible_host=${yandex_compute_instance.k8s-worker4.network_interface.0.nat_ip_address}  # ip=10.3.0.5 etcd_member_name=etcd5

    [kube_control_plane]
    k8s-master1

    [etcd]
    k8s-master1

    [kube_node]
    k8s-worker1
    k8s-worker2
    k8s-worker3
    k8s-worker4

    [calico_rr]

    [k8s_cluster:children]
    kube_control_plane
    kube_node
    calico_rr


    DOC
  filename = "../12-kubernetes-04-install-part-2/kubespray/inventory/12.4/inventory.ini"

  depends_on = [
    yandex_compute_instance.k8s-master1
    ,yandex_compute_instance.k8s-worker1
    ,yandex_compute_instance.k8s-worker2
    ,yandex_compute_instance.k8s-worker3
    ,yandex_compute_instance.k8s-worker4
  ]
}



